"""Copy a small, curated set of benchmark generations into results/samples/ so the
repo carries at-a-glance visual evidence without shipping the full 13 GB. The full
set is regenerated by the pipeline; this is a fixed, explicit selection chosen to
back the three findings in the README, not a cherry-pick for flattery.

Run after the benchmark exists (reads results/benchmark/generations and the identity
gallery). Idempotent. Warns if any selected image is near-grayscale, so a stale
pre-color-fix generation cannot slip into the gallery.
"""

from __future__ import annotations

import shutil

import numpy as np
from PIL import Image

from dcfaces.paths import BENCHMARK_DIR, IDENTITY_GALLERY, RESULTS_DIR

GEN = BENCHMARK_DIR / "generations"
SAMPLES = RESULTS_DIR / "samples"
SEED = 42


def gen_path(method: str, idn: str, prompt_key: str) -> "object":
    return GEN / method / idn / prompt_key / f"seed_{SEED}.png"


# (subfolder, destination filename, source path). Kept fully explicit on purpose.
SELECTION: list[tuple[str, str, object]] = []

# references — so identity preservation in the other panels is judgeable
for i in (1, 2, 3, 4, 5):
    idn = f"id_{i:03d}"
    SELECTION.append(("references", f"{idn}.jpg", IDENTITY_GALLERY / idn / "ref.jpg"))

# trade-off — one person, one race-control prompt, every method
for method in ("pulid_only", "pulid_delayed", "pulid_with_demo_lora", "photomaker",
               "ip_adapter_faceid", "dreambooth_lora", "dreambooth_lora_with_demo", "hyperlora"):
    SELECTION.append(("trade-off", f"{method}.png", gen_path(method, "id_002", "race_east_asian")))

# rescue — stacking the demo LoRA does not shift race; delayed injection does
for idn in ("id_001", "id_005"):
    for method in ("pulid_only", "pulid_with_demo_lora", "pulid_delayed"):
        SELECTION.append(("rescue", f"{idn}__{method}.png", gen_path(method, idn, "race_east_asian")))

# age limit — delayed injection cannot move structural age; DreamBooth can
for key in ("age_20", "age_80"):
    for method in ("pulid_delayed", "dreambooth_lora"):
        SELECTION.append(("age-limit", f"{key}__{method}.png", gen_path(method, "id_001", key)))

# accessory control — varies by method
for key, label in (("accessory_0", "glasses"), ("accessory_3", "cap")):
    for method in ("photomaker", "pulid_only"):
        SELECTION.append(("accessory", f"{label}__{method}.png", gen_path(method, "id_004", key)))


def saturation(path) -> float:
    return float(np.asarray(Image.open(path).convert("HSV"))[..., 1].mean())


CAPTIONS = {
    "references": "The reference photo for each identity used below (FFHQ, public domain). Identity preservation in the other panels is judged against these.",
    "trade-off": "One identity (id_002), the prompt \"depicted as East Asian\", every method, same seed. PuLID locks the reference and ignores the race request; HyperLoRA follows the prompt but drifts off the reference.",
    "rescue": "pulid_only vs pulid_with_demo_lora vs pulid_delayed on the same race prompt. Stacking the demographic LoRA does not shift race; holding identity injection off for the first 13 steps (delayed) does.",
    "age-limit": "The rescue is attribute-dependent. At age_20 and age_80, pulid_delayed cannot move the structural age (it stays identity-locked), while a per-identity DreamBooth LoRA can.",
    "accessory": "Accessory control (round glasses, baseball cap) differs by method: PhotoMaker renders the accessory readily, PuLID resists it in favour of the locked reference.",
}


def main() -> None:
    missing, low_sat = [], []
    for folder, name, src in SELECTION:
        if not src.exists():
            missing.append(str(src))
            continue
        dst = SAMPLES / folder / name
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, dst)
        if src.suffix == ".png" and saturation(src) < 12:
            low_sat.append(f"{folder}/{name} (saturation {saturation(src):.0f})")

    # index
    lines = ["# Sample gallery\n",
             "A curated subset of the benchmark generations (the full ~18k images are not",
             "shipped; regenerate them with the pipeline). Selection is fixed in",
             "`scripts/make_sample_gallery.py`. All on SDXL 1.0 + fp16-fix VAE, seed 42",
             "(HyperLoRA on RealVisXL v4.0).\n"]
    for folder in ("references", "trade-off", "rescue", "age-limit", "accessory"):
        lines.append(f"## {folder}\n")
        lines.append(CAPTIONS[folder] + "\n")
    (SAMPLES).mkdir(parents=True, exist_ok=True)
    (SAMPLES / "README.md").write_text("\n".join(lines) + "\n")

    n = sum(1 for f, n_, s in SELECTION if s.exists())
    print(f"copied {n} images to {SAMPLES}")
    if missing:
        print("MISSING sources:", *missing, sep="\n  ")
    if low_sat:
        print("WARNING near-grayscale (should have been color-fixed):", *low_sat, sep="\n  ")
    if not missing and not low_sat:
        print("GALLERY_OK")


if __name__ == "__main__":
    main()
